/**
 * Shared abstract hygiene used by ingest (scripts/fetch.js) and the
 * abstract backfill (scripts/fix-junk-abstracts.mjs).
 *
 * Three distinct failure modes were measured in the live corpus (2026-05):
 *   1. Springer/BMC RSS ships ONLY the structured-abstract section headings —
 *      "Background Methods Results Conclusions", "Graphical abstract" — with
 *      the body text dropped. These are DOI-keyed → recoverable from the
 *      OpenAlex/Crossref cascade.
 *   2. Nature "Scientific Reports" RSS ships citation boilerplate as the
 *      description: "Scientific Reports, Published online: <date>; doi:10...; <title>".
 *      Also DOI-recoverable.
 *   3. News/pop-sci feeds (Futurism, ScienceAlert, PopSci, ...) append junk
 *      tails: "The post X appeared first on Y." and the ScienceAlert
 *      "...never generated by AI. Don't miss a story, subscribe here." These
 *      have no real abstract; we only strip the tail.
 */

// Section headings that appear in structured abstracts. If an "abstract" is
// composed ENTIRELY of these (plus stray punctuation), it carries no content.
const HEADING_WORDS = new Set([
  'background', 'introduction', 'objective', 'objectives', 'aim', 'aims',
  'purpose', 'rationale', 'method', 'methods', 'methodology', 'materials',
  'material', 'result', 'results', 'conclusion', 'conclusions', 'discussion',
  'summary', 'graphical', 'abstract', 'significance', 'importance', 'findings',
  'finding', 'interpretation', 'funding', 'design', 'setting', 'settings',
  'participants', 'intervention', 'interventions', 'outcome', 'outcomes',
  'highlights', 'highlight', 'scope', 'context', 'and', 'the', 'of', 'a',
]);

/**
 * True when `text` is not a usable abstract: empty, heading-only, or a
 * journal citation stub. A null/undefined input is treated as junk.
 */
export function isJunkAbstract(text) {
  if (!text || typeof text !== 'string') return true;
  const s = text.replace(/\s+/g, ' ').trim();
  if (!s) return true;

  // (2) Nature/journal "Published online: <date>; doi:10..." citation stub.
  // Anchored near the start so a real abstract that merely mentions the phrase
  // later is not caught.
  if (/^.{0,90}Published online:\s*[^;]{3,40};\s*doi:\s*10\.\d{4}/i.test(s)) return true;

  // (1) Heading-only stub: every alphabetic token is a section heading.
  const words = s.toLowerCase().match(/[a-z][a-z-]*/g) || [];
  if (words.length > 0 && words.length <= 12 && words.every(w => HEADING_WORDS.has(w))) {
    return true;
  }

  // Catch-all: essentially no prose. Fewer than ~6 words AND under 40 chars of
  // letters is not an abstract (e.g. "Graphical abstract", "N/A", "See PDF").
  const letterCount = (s.match(/[a-zA-Z]/g) || []).length;
  if (words.length < 6 && letterCount < 40) return true;

  return false;
}

/**
 * Remove known feed/CMS boilerplate tails. Does NOT lengthen short teasers —
 * news posts simply have no abstract — it just stops the junk from rendering.
 */
export function stripBoilerplateTail(text) {
  if (!text || typeof text !== 'string') return text;
  let s = text;
  // WordPress syndication tail (Futurism, Popular Science, ...):
  //   "<teaser>. The post <Title> appeared first on <Publication>."
  // Tightly matched to the plugin's exact output, NOT ordinary prose:
  //   - must START a new sentence (preceded by . ! ? or string start),
  //   - a SPACE must follow "post" (so it never eats "post-translational",
  //     "post-mortem", "post-hoc" — those have a hyphen, not a space),
  //   - "appeared first on" must be followed by a Capitalized publication name.
  // The preceding sentence's terminator is preserved (returned via `lead`).
  s = s.replace(
    /([.!?]\s|^)\s*The post\s.{1,160}?\sappeared first on\s+[A-Z][^.]{0,50}\.?\s*$/,
    (_m, lead) => (lead && lead.trim() ? lead.trim() : ''),
  );
  // ScienceAlert standardized tail (literal unique phrase — negligible FP risk).
  s = s.replace(/\s*ScienceAlert stories are written,?\s*fact-checked,?\s*and edited by humans,?\s*never generated by AI\.?.*$/i, '');
  s = s.replace(/\s*Don'?t miss a story,?\s*subscribe here\.?\s*$/i, '');
  // NOTE: deliberately no generic "Read more"/"Continue reading" strip — those
  // are ordinary English ("...encourage patients to read more about X") and an
  // end-anchored match truncates real abstracts.
  return s.trim();
}

/**
 * Convenience for ingest: strip tails, then return null if what remains is
 * junk. Callers treat null as "no abstract" so the enrichment cascade fills it.
 */
export function cleanForStore(text) {
  if (!text || typeof text !== 'string') return null;
  const stripped = stripBoilerplateTail(text);
  if (isJunkAbstract(stripped)) return null;
  return stripped;
}
